colours:
    message: 'e'
    playername: '7'
global:
    join:
    - 'Look out, it's %p joining the server!'
    - 'Holy batman, %p has appeared!'
    - 'Oh! Look who decided to join us today! (%p)'
    leave:
    - 'Aww, it seems %p has left us.'
    - 'It seems %p has hit the bucket, not in a literal sence.'
    - '%p just disappeared out of thin air!'
player:
    WinneonSword:
        join:
        - 'Would you look at that! %p has joined!'
        - 'The one and only %p has appeared!'
        - 'I don't know, but it looks like %p has come to join us!'
        leave:
        - 'Wave goodbye to %p!'
        - '%p has other important things to do now.'
        - 'It appears a certain individual has left us for now. (%p)'